return {
  -- {
  --   "zbirenbaum/copilot.lua",
  --   cmd = "Copilot",
  --   build = ":Copilot auth",
  --   opts = {
  --     panel = {
  --       enabled = true,
  --       auto_refresh = false,
  --       keymap = {
  --         jump_prev = "[[",
  --         jump_next = "]]",
  --         accept = "<CR>",
  --         refresh = "gr",
  --         open = "<M-CR>",
  --       },
  --       layout = {
  --         position = "bottom", -- | top | left | right
  --         ratio = 0.4,
  --       },
  --     },
  --     suggestion = {
  --       auto_trigger = true,
  --       keymap = {
  --         accept = "<C-j>",
  --         prev = "<C-[>",
  --         next = "<C-]>",
  --         dismiss = "<C-\\>",
  --       },
  --     },
  --     filetypes = {
  --       yaml = false,
  --       markdown = false,
  --       help = false,
  --       gitcommit = false,
  --       gitrebase = false,
  --       hgcommit = false,
  --       svn = false,
  --       cvs = false,
  --       ["."] = false,
  --     },
  --     copilot_node_command = "node", -- Node.js version must be > 16.x
  --     server_opts_overrides = {},
  --   },
  -- },
}
